name: Google Chat Webhook

on:
  workflow_call:
    inputs:
      header_image:
        description: "Custom header image URL (optional)"
        default: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
        required: false
        type: string
      reply_option:
        description: "new_thread or same_thread (optional, default same_thread)"
        default: 'same_thread'
        required: false
        type: string
    secrets:
      google_chat_webhook:
        required: true

  pull_request:
    types: [opened, synchronize, reopened]

  pull_request_review:
    types: [submitted]

jobs:
  notify-google-chat:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare inputs
        id: prepare_inputs
        run: |
          echo "HEADER_IMAGE=${{ inputs.header_image }}" >> $GITHUB_ENV
          
          if [ "${{ inputs.reply_option }}" == "new_thread" ]; then
            echo "REPLY_OPTION=MESSAGE_REPLY_OPTION_UNSPECIFIED" >> $GITHUB_ENV
          else
            echo "REPLY_OPTION=REPLY_MESSAGE_FALLBACK_TO_NEW_THREAD" >> $GITHUB_ENV
          fi

          # Definir mensagem do evento baseado no tipo
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            case "${{ github.event.action }}" in
              opened)
                echo 'PR_EVENT=ðŸ“Œ Pull Request Created' >> $GITHUB_ENV
                ;;
              synchronize)
                echo 'PR_EVENT=ðŸ”„ Pull Request Updated' >> $GITHUB_ENV
                ;;
              reopened)
                echo 'PR_EVENT=ðŸ”“ Pull Request Reopened' >> $GITHUB_ENV
                ;;
              *)
                echo 'PR_EVENT=ðŸ“Œ Pull Request Event' >> $GITHUB_ENV
                ;;
            esac
          
          elif [ "${{ github.event_name }}" == "pull_request_review" ]; then
            case "${{ github.event.review.state }}" in
              approved)
                echo 'PR_EVENT=âœ… Pull Request Approved' >> $GITHUB_ENV
                ;;
              commented)
                echo 'PR_EVENT=ðŸ’¬ Pull Request Commented' >> $GITHUB_ENV
                ;;
              changes_requested)
                echo 'PR_EVENT=âŒ Pull Request Changes Requested' >> $GITHUB_ENV
                ;;
              *)
                echo 'PR_EVENT=ðŸ“Œ Pull Request Reviewed' >> $GITHUB_ENV
                ;;
            esac
          fi

      - name: Send Notification to Google Chat on PR Events
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "cardsV2": [{
                  "cardId": "pr-notification",
                  "card": {
                    "header": {
                      "title": "GitHub Pull Request",
                      "subtitle": "'"${{ github.repository }}"'",
                      "imageUrl": "'"$HEADER_IMAGE"'"
                    },
                    "sections": [{
                      "widgets": [{
                        "textParagraph": {
                          "text": "<b>'"$PR_EVENT"'</b> by <b>@${{ github.actor }}</b>:<br><b>'"${{ github.event.pull_request.title }}"'</b>"
                        }
                      }]
                    },
                    {
                      "widgets": [{
                        "buttonList": {
                          "buttons": [{
                            "text": "View Pull Request",
                            "onClick": {
                              "openLink": {
                                "url": "'"${{ github.event.pull_request.html_url }}"'"
                              }
                            }
                          }]
                        }
                      }]
                    }]
                  }
                }],
                "thread": {
                  "threadKey": "'"${{ github.repository }}/${{ github.event.pull_request.number }}"'"
                }
              }' \
          "${{ secrets.google_chat_webhook }}&messageReplyOption=$REPLY_OPTION"
